spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/inventory_db}
    username: ${SPRING_DATASOURCE_USERNAME:inventory_user}
    password: ${SPRING_DATASOURCE_PASSWORD:inventory_pass}

external:
  products-service:
    base-url: ${EXTERNAL_PRODUCTS_SERVICE_BASE_URL:http://host.docker.internal:8080}
    api-key: ${PRODUCTS_API_KEY:your-secret-api-key-here}

app:
  api:
    key: ${APP_API_KEY:your-secret-api-key-here}

logging:
  level:
    root: INFO
    com.inventory: INFO